### ISSUE TITLE
Spilt up Lexer, Parser and Interpreter

### ISSUE THREAD

**Issue by SimpleBinary** [Solar-language/Solar#10]
@Dandigit Splitting up the interpreter has caused an Solar error saying that parser has no attribute Parser in Solar, I'm going to put that in a BETA file inside src, but keep the one file version as the stable version while we get that fixed.

**Comment by SimpleBinary** [comment]
@Dandigit I have worked out that `parser` is a built in python library, maybe it is only for Windows.

**Comment by SimpleBinary** [comment]
I'm going to rename them solarParser, solarLexer and solarInterpreter as to avoid confusion.

**Comment by Dandigit** [comment]
@SimpleBinary I've just updated the fix to be less obtrusive - I kept all names as they were before, except `parser` is now named `parser_` to signal that `parser` is a built in library.
