### ISSUE TITLE
Bug: Python External Printing

### ISSUE THREAD

**Issue by SimpleBinary** [Solar-language/Solar#14]
**Describe the bug**
When printing in python, it prints something along the lines of `{"type": String, "value": "x",}` instead of `x`.

**To Reproduce**
1. Import a python file that prints something
2. Run the function that prints something

**Comment by SimpleBinary** [comment]
@Dandigit

**Comment by Dandigit** [comment]
I think I know why this is occurring. Gimme a sec to open a PR.

**Comment by Dandigit** [comment]
Fixed in #15.

**Comment by SimpleBinary** [comment]
@Dandigit I just looked at VSCode marketplace and solar has 13 downloads. 😀

**Comment by Dandigit** [comment]
@SimpleBinary 🎉
