### ISSUE TITLE
What to do from here?

### ISSUE THREAD

**Issue by SimpleBinary** [Solar-language/Solar#3]
I'm having some trouble working out what to do once I have got the ast. I am planning to just interpret using the ast not compile to bytecode, but I don't know what I should do next. Any help is greatly appreciated.
@SimpleBinary 
**Owner of this Orginisation**

**Comment by Dandigit** [comment]
@SimpleBinary Sure!
I haven't read through your code yet - once I do I'll provide a more detailed answer. It sounds like what you're looking for is the [Visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern).

**Comment by Dandigit** [comment]
See #4.

**Comment by BonfireScratch** [comment]
@SimpleBinary I guess you should want to enable running from console using `sys.argv[1]`
