### ISSUE TITLE
Use '+', '-', etc. instead of 'add', 'subtract' etc.

### ISSUE THREAD

**Issue by Dandigit** [Solar-language/Solar#6]
Traditionally, in Lisps, the functions which replace traditional operators use a symbol, like `+`, instead of a name, like `add`. I think that this:
```
(put (+ 2 (- 4 3)))
```
...is a fair bit more practical than this:
```
(put (add 2 (subtract 4 3)))
```
I suppose this is pretty subjective though - I'd like to hear what you think. 

(By the way, you may have to modify the parser to accept symbols in identifiers if you agree with this.)

**Comment by Dandigit** [comment]
@SimpleBinary

**Comment by SimpleBinary** [comment]
I agree, it does look more practical. I will try and update it asap. @Dandigit.

**Comment by SimpleBinary** [comment]
@ Dandigit Done with +, -, *, /, % but not float, int, str.
